# flask ENV
DEBUG = True
SECRET_KEY = 'dev'

# the following is forced true if debug is true
TEMPLATES_AUTO_RELOAD = True
# PROPAGATE_EXCEPTIONS = True
# PRESERVE_CONTEXT_ON_EXCEPTION = True
# TRAP_BAD_REQUEST_ERRORS = True
# JSONIFY_PRETTYPRINT_REGULAR = True

# database
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 0000
MYSQL_DATABASE_USER = ''
MYSQL_DATABASE_PASSWORD = ''
MYSQL_DATABASE_DB = ''
MYSQL_DATABASE_CHARSET = ''
