# flask ENV
ENV = "development"
DEBUG = True
SECRET_KEY = 'dev'


# database
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 3306
MYSQL_DATABASE_USER = ''
MYSQL_DATABASE_PASSWORD = ''
MYSQL_DATABASE_DB = ''
MYSQL_DATABASE_CHARSET = ''